export default {
  name:'contact',
  title:'Contact',
  type:'document',
  fields:[
      {
          name:'email',
          title:'Email',
          type:'string'
      },
      {
          name:'messenger',
          title:'Messenger',
          type:'string'
      },
      {
          name:'whatsapp',
          title:'Whatsapp',
          type:'string'
      },
      {
        name:'facebook',
        title:'Facebook',
        type:'string'
      },
      {
        name:'instagram',
        title:'Instagram',
        type:'string'
      },
      {
        name:'twitter',
        title:'Twitter',
        type:'string'
      },
      {
        name:'linkedin',
        title:'Linkedin',
        type:'string'
      },
      {
        name:'github',
        title:'Github',
        type:'string'
      }
  ]
}